### PR TITLE
chore: project structure and deps

### PR DESCRIPTION
**Pull request by epreston**
Project cleanup before minor revision.

- Update license files for all venders
- Add CI badge
- Organise dependencies
- add standard tool configuration files
- github templates commmon to playcanvas projects

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by epreston** [comment]
If this is all acceptable, including the CI PR, it would be nice to bump this to 1.0.3 and add a commit to tag it at 1.0.3.

This could be the starting point before major changes to support spine 4.1 on engine 1.65.

**Review by willeastcott — APPROVED** [review]
LGTM!

**Comment by willeastcott** [comment]
A note on history. This repo was setup to use Gulp because it was in the days before we adopted Rollup for our standard build system.

**Comment by epreston** [comment]
We'll make it standard.

**Pull request merged**
