### PR TITLE
Spine support for version 4.0

### LINKED ISSUE #52: Support for Spine 4.x now that it's stable?
Just wondering if there's any plans to support 4.x now that it's been promoted to stable.

### PR DESCRIPTION
**Pull request by mvaligursky**
Fixes: https://github.com/playcanvas/playcanvas-spine/issues/52

- based on Spine version 4.0.16 downloaded from 
`https://unpkg.com/@esotericsoftware/spine-core@4.0.*/dist/iife/spine-core.js`
- added build steps and an example.

**TODO**: 
- the example is crashing due to Spine API changes, and so the integration needs to be fixed to work with it. (most notable changes are here: https://github.com/EsotericSoftware/spine-runtimes/blob/4.0/CHANGELOG.md#c-2 )
- the downloaded spine-core.js is now ES6 and uses classes .. we probably need to change the build process and transpile the result to ES5

Screenshot 2021-12-02 at 12 23 31

### CODE REVIEW

**Comment by epreston** [comment]
Can we merge what you have so far so we can build off of it ?  
Whats the best way to contribute to this ?

**Comment by mvaligursky** [comment]
I cannot merge it to main as it does not work .. but it's in this branch .. so you should be able to work from there?
https://github.com/playcanvas/playcanvas-spine/tree/mvaligursky-spine-40

**Comment by mvaligursky** [comment]
But looking at this PR .. I only added a spine 4.0 based example, which is not needed yet, and tried to extend the build to cover 4.0 to follow 3.8 path, but that does not work at all. So I think this can be started from scratch, as a different way to build 4.0 is needed as its module based now.

**Comment by epreston** [comment]
I got 4.1 sorted and a bit of a structure to support multiple versions.

Here's a demo: https://github.com/epreston/playcanvas-spine/tree/rollup-build-system

See the `examples/spine/raptor41.html`

Capture

**Comment by epreston** [comment]
The "getImage" error above is that the TextureAtlas now has 1 param.  Then you need to cycle through the array of "pages" in the atlas and tell it to load the images.  It used to do it in one go.  This was so loading could be done on a worker and the game thread that owns the images could slot them in.

**Comment by epreston** [comment]
I put the important changes in a single commit see: commit 539ff9c85e68e288f58adfd66cab539068183eeb

**Pull request closed without merging**
