### PR TITLE
Add Spine 4.0 Plugin Support

### PR DESCRIPTION
**Pull request by epreston**
Add Spine 4.0 Plugin Support

- Add media and examples for Spine 4.0 runtime
- Update build system to create 4.0 plugin
- Add prebuilt plugin
- Update docs, minor tool adjustments
- New Owl demo is kinda fun.

Replaces: #78

Fixes a gap in the support matrix.

I confirm I have read the [contributing guidelines](https://github.com/playcanvas/engine/blob/master/.github/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by epreston** [comment]
@mvaligursky had to redo the PR so it was up to date with the 4.1 support.  
Nearly have it working except 4.0 demos will not display.  No errors.  
I think it might have something to do with the texture.

**Comment by epreston** [comment]
Raptor 4.0 should look identical to Raptor 4.1 demo.  Nothing displays for 4.0
Owl 4.0 demo should look like the following.  I hope to use the owl so each version has a unique looking demo.  Currently, nothing displayed for 4.0 but everything loaded, no errors.
 
OwlDemoEndState

**Comment by epreston** [comment]
If I modify the json file version of the owl demo and use 4.1 library, the owl demo works without modification.  If I use the 4.0 library, no errors, but nothing displays.

CPT2309150706-450x356

To reproduce, modify `spine40/demos.json`, 4th line:
```
    "spine": "4.1.23",
```

In the owl40.html modify the 43 nd line:
```
new pc.Asset("playcanvas-spine.4.1.js", "script", { url: "../build/playcanvas-spine.4.1.js" }),
```

**Comment by epreston** [comment]
For version 4.0, it looks like textures are accessed through the "page" property.  For RegionAttachment and MeshAttachment we need to make the following adjustments.

The following:
```
// create / assign material
if (attachment.region && attachment.region.texture) {
    const texture = attachment.region.texture.pcTexture;
```

Becomes:
```
// create / assign material
if (attachment.region && attachment.region.page.texture) {
    const texture = attachment.region.page.texture.pcTexture;
```

**Comment by epreston** [comment]
Ready for review, please be sure to check out the Owl demo.

If two raptor demos is confusing, I can remove the 4.0 version.

**Comment by epreston** [comment]
One area of improvement that needs an engine / graphics expert.  The grey outline makes me think the pre-multiplied alpha is wrong.  The plugin just assumes this is:

```js
material.blendType = pc.BLEND_PREMULTIPLIED;
```

I've seen data files that have a "pma" attribute for textures, which we could read and honour.  Thing is, this is something that I get wrong all the time.  It could just be that its on a grey background.  I don't know.  

The first screenshot above is from the original spine demo, outlines are nice and crisp.  In that demo they are using an alphaTest threshold of 0.5, I don't know what the equivalent or how that is achieved in PlayCanvas Engine.

**Review by mvaligursky — APPROVED** [review]
Top contribution, much appreciated!

**Pull request merged**
